In [3]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [4]:
df = pd.read_csv("../data/raw/tickets.csv")
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [9]:
df.columns

Index(['Ticket ID', 'Customer Name', 'Customer Email', 'Customer Age',
       'Customer Gender', 'Product Purchased', 'Date of Purchase',
       'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status',
       'Resolution', 'Ticket Priority', 'Ticket Channel',
       'First Response Time', 'Time to Resolution',
       'Customer Satisfaction Rating'],
      dtype='object')

In [11]:
df.shape

(8469, 17)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   object
 2   Customer Email                8469 non-null   object
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   object
 5   Product Purchased             8469 non-null   object
 6   Date of Purchase              8469 non-null   object
 7   Ticket Type                   8469 non-null   object
 8   Ticket Subject                8469 non-null   object
 9   Ticket Description            8469 non-null   object
 10  Ticket Status                 8469 non-null   object
 11  Resolution                    2769 non-null   object
 12  Ticket Priority               8469 non-null   object
 13  Ticket Channel                8469 non-null   object
 14  First Response Time           5650 non-null   object
 15  Time to Resolution            2769 non-null   object
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), object(14)
memory usage: 1.1+ MB

In [13]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df.columns

Index(['ticket_id', 'customer_name', 'customer_email', 'customer_age',
       'customer_gender', 'product_purchased', 'date_of_purchase',
       'ticket_type', 'ticket_subject', 'ticket_description', 'ticket_status',
       'resolution', 'ticket_priority', 'ticket_channel',
       'first_response_time', 'time_to_resolution',
       'customer_satisfaction_rating'],
      dtype='object')

In [14]:
df.isna().sum().sort_values(ascending=False)

customer_satisfaction_rating    5700
resolution                      5700
time_to_resolution              5700
first_response_time             2819
ticket_id                          0
customer_name                      0
customer_email                     0
customer_age                       0
customer_gender                    0
ticket_subject                     0
ticket_type                        0
date_of_purchase                   0
product_purchased                  0
ticket_priority                    0
ticket_status                      0
ticket_description                 0
ticket_channel                     0
dtype: int64

In [15]:
df.dtypes

ticket_id                         int64
customer_name                    object
customer_email                   object
customer_age                      int64
customer_gender                  object
product_purchased                object
date_of_purchase                 object
ticket_type                      object
ticket_subject                   object
ticket_description               object
ticket_status                    object
resolution                       object
ticket_priority                  object
ticket_channel                   object
first_response_time              object
time_to_resolution               object
customer_satisfaction_rating    float64
dtype: object

In [16]:
df['ticket_type'].value_counts()

ticket_type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

In [17]:
df['ticket_priority'].value_counts()

ticket_priority
Medium      2192
Critical    2129
High        2085
Low         2063
Name: count, dtype: int64

In [18]:
df['time_to_resolution'].describe()

count                    2769
unique                   2728
top       2023-06-01 17:14:42
freq                        3
Name: time_to_resolution, dtype: object

In [19]:
df['time_to_resolution'].dropna().head(10)

2     2023-06-01 18:05:38
3     2023-06-01 01:57:40
4     2023-06-01 19:53:42
10    2023-05-31 23:51:49
11    2023-06-01 09:27:51
14    2023-05-31 23:08:55
16    2023-06-01 15:58:59
19    2023-06-01 20:29:04
28    2023-06-01 06:03:17
29    2023-06-01 18:23:17
Name: time_to_resolution, dtype: object

In [20]:
df['first_response_time'].dropna().head(10)

0     2023-06-01 12:15:36
1     2023-06-01 16:45:38
2     2023-06-01 11:14:38
3     2023-06-01 07:29:40
4     2023-06-01 00:12:42
8     2023-06-01 10:32:47
9     2023-06-01 09:25:48
10    2023-06-01 17:46:49
11    2023-06-01 12:05:51
12    2023-06-01 19:03:53
Name: first_response_time, dtype: object

In [21]:
import pandas as pd

def convert_to_hours(x):
    try:
        if pd.isna(x):
            return None
        x = str(x).lower()
        if "day" in x:
            days = int(x.split("day")[0].strip())
            return days * 24
        if "hour" in x:
            return float(x.split("hour")[0].strip())
        if ":" in x:
            h, m, s = x.split(":")
            return int(h) + int(m)/60
        return float(x)
    except:
        return None

df['resolution_time_hours'] = df['time_to_resolution'].apply(convert_to_hours)

In [22]:
df['resolution_time_hours'].describe()

count       0
unique      0
top       NaN
freq      NaN
Name: resolution_time_hours, dtype: object

In [23]:
df['date_of_purchase'] = pd.to_datetime(df['date_of_purchase'], errors='coerce')
df['time_to_resolution'] = pd.to_datetime(df['time_to_resolution'], errors='coerce')

df[['date_of_purchase', 'time_to_resolution']].head()

  date_of_purchase  time_to_resolution
0       2021-03-22                 NaT
1       2021-05-22                 NaT
2       2020-07-14 2023-06-01 18:05:38
3       2020-11-13 2023-06-01 01:57:40
4       2020-02-04 2023-06-01 19:53:42

In [24]:
df['resolution_time_hours'] = (
    df['time_to_resolution'] - df['date_of_purchase']
).dt.total_seconds() / 3600

In [25]:
df['resolution_time_hours'].describe()

count     2769.000000
mean     21234.361898
std       5075.863353
min      12438.464444
25%      16808.266111
50%      21306.388056
75%      25613.881944
max      29947.068889
Name: resolution_time_hours, dtype: float64

In [26]:
df['resolution_time_hours_capped'] = df['resolution_time_hours'].clip(upper=2160)

In [27]:
df['resolution_time_hours_capped'].describe()

count    2769.0
mean     2160.0
std         0.0
min      2160.0
25%      2160.0
50%      2160.0
75%      2160.0
max      2160.0
Name: resolution_time_hours_capped, dtype: float64

In [28]:
df_resolution = df.dropna(subset=['resolution_time_hours_capped']).copy()

In [29]:
df['ticket_text'] = (
    df['ticket_subject'].fillna('') + ' ' +
    df['ticket_description'].fillna('')
)

df['ticket_text'].head()

0    Product setup I'm having an issue with the {pr...
1    Peripheral compatibility I'm having an issue w...
2    Network problem I'm facing a problem with my {...
3    Account access I'm having an issue with the {p...
4    Data loss I'm having an issue with the {produc...
Name: ticket_text, dtype: object

In [30]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = text.lower()                         # lowercase
    text = re.sub(r'[^a-z\s]', '', text)        # remove punctuation & numbers
    words = text.split()
    words = [w for w in words if w not in stop_words]  # remove stopwords
    words = [lemmatizer.lemmatize(w) for w in words]   # lemmatize
    return " ".join(words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\viraj\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\viraj\AppData\Roaming\nltk_data...

In [31]:
df['clean_ticket_text'] = df['ticket_text'].apply(clean_text)

df[['ticket_text', 'clean_ticket_text']].head()

,ticket_text,clean_ticket_text
0,Product setup I'm having an issue with the {pr...,product setup im issue productpurchased please...
1,Peripheral compatibility I'm having an issue w...,peripheral compatibility im issue productpurch...
2,Network problem I'm facing a problem with my {...,network problem im facing problem productpurch...
3,Account access I'm having an issue with the {p...,account access im issue productpurchased pleas...
4,Data loss I'm having an issue with the {produc...,data loss im issue productpurchased please ass...

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=3000,
    ngram_range=(1, 2)
)

X_text = tfidf.fit_transform(df['clean_ticket_text'])

X_text.shape

(8469, 3000)

In [33]:
y_category = df['ticket_type']

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_text,
    y_category,
    test_size=0.2,
    random_state=42,
    stratify=y_category
)

In [35]:
from sklearn.linear_model import LogisticRegression

model_cat = LogisticRegression(max_iter=1000)
model_cat.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [36]:
from sklearn.metrics import classification_report, accuracy_score

y_pred = model_cat.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.2066115702479339
                      precision    recall  f1-score   support

     Billing inquiry       0.20      0.20      0.20       327
Cancellation request       0.20      0.19      0.20       339
     Product inquiry       0.22      0.21      0.21       328
      Refund request       0.18      0.19      0.19       351
     Technical issue       0.23      0.24      0.24       349

            accuracy                           0.21      1694
           macro avg       0.21      0.21      0.21      1694
        weighted avg       0.21      0.21      0.21      1694

In [39]:
from sklearn.preprocessing import OneHotEncoder
from scipy.sparse import hstack

cat_features = df[['ticket_channel', 'product_purchased', 'customer_gender']]

encoder = OneHotEncoder(handle_unknown='ignore', sparse=True)

X_cat = encoder.fit_transform(cat_features)

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [6]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=True)

In [7]:
cat_features = df[['ticket_channel', 'product_purchased', 'customer_gender']]

X_cat = encoder.fit_transform(cat_features)
X_cat.shape

KeyError: "None of [Index(['ticket_channel', 'product_purchased', 'customer_gender'], dtype='object')] are in the [columns]"

In [8]:
import pandas as pd

df = pd.read_csv("../data/raw/tickets.csv")

In [9]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [10]:
df['ticket_text'] = (
    df['ticket_subject'].fillna('') + ' ' +
    df['ticket_description'].fillna('')
)

In [14]:
df['clean_ticket_text'] = df['ticket_text'].apply(clean_text)

In [12]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    words = [lemmatizer.lemmatize(w) for w in words]
    return " ".join(words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\viraj\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\viraj\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [13]:
df['clean_ticket_text'] = df['ticket_text'].apply(clean_text)

df[['ticket_text', 'clean_ticket_text']].head()

,ticket_text,clean_ticket_text
0,Product setup I'm having an issue with the {pr...,product setup im issue productpurchased please...
1,Peripheral compatibility I'm having an issue w...,peripheral compatibility im issue productpurch...
2,Network problem I'm facing a problem with my {...,network problem im facing problem productpurch...
3,Account access I'm having an issue with the {p...,account access im issue productpurchased pleas...
4,Data loss I'm having an issue with the {produc...,data loss im issue productpurchased please ass...

In [15]:
X_text.shape

NameError: name 'X_text' is not defined

In [16]:
import pandas as pd

df = pd.read_csv("../data/raw/tickets.csv")

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [17]:
df['ticket_text'] = (
    df['ticket_subject'].fillna('') + ' ' +
    df['ticket_description'].fillna('')
)

In [18]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    words = [lemmatizer.lemmatize(w) for w in words]
    return " ".join(words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\viraj\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\viraj\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [19]:
df['clean_ticket_text'] = df['ticket_text'].apply(clean_text)

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=3000, ngram_range=(1, 2))
X_text = tfidf.fit_transform(df['clean_ticket_text'])

X_text.shape

(8469, 3000)

In [21]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=True)

cat_features = df[['ticket_channel', 'product_purchased', 'customer_gender']]
X_cat = encoder.fit_transform(cat_features)

X_cat.shape

(8469, 49)

In [22]:
from scipy.sparse import hstack

X_combined = hstack([X_text, X_cat])
X_combined.shape

(8469, 3049)

In [23]:
from sklearn.model_selection import train_test_split

y_category = df['ticket_type']

X_train, X_test, y_train, y_test = train_test_split(
    X_combined,
    y_category,
    test_size=0.2,
    random_state=42,
    stratify=y_category
)

In [24]:
from sklearn.linear_model import LogisticRegression

model_cat = LogisticRegression(max_iter=2000, n_jobs=-1)
model_cat.fit(X_train, y_train)

c:\Users\viraj\OneDrive\Desktop\support-ticket-intelligence\customer-support-ticket-intelligence\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

LogisticRegression(max_iter=2000, n_jobs=-1)

In [25]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = model_cat.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.19893742621015348
                      precision    recall  f1-score   support

     Billing inquiry       0.20      0.18      0.19       327
Cancellation request       0.19      0.20      0.19       339
     Product inquiry       0.19      0.18      0.19       328
      Refund request       0.18      0.20      0.19       351
     Technical issue       0.23      0.23      0.23       349

            accuracy                           0.20      1694
           macro avg       0.20      0.20      0.20      1694
        weighted avg       0.20      0.20      0.20      1694

In [26]:
y_priority = df['ticket_priority']

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_combined,
    y_priority,
    test_size=0.2,
    random_state=42,
    stratify=y_priority
)

In [28]:
from sklearn.linear_model import LogisticRegression

model_priority = LogisticRegression(max_iter=2000, n_jobs=-1)
model_priority.fit(X_train, y_train)

c:\Users\viraj\OneDrive\Desktop\support-ticket-intelligence\customer-support-ticket-intelligence\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

LogisticRegression(max_iter=2000, n_jobs=-1)

In [29]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = model_priority.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.2550177095631641
              precision    recall  f1-score   support

    Critical       0.24      0.23      0.23       426
        High       0.27      0.27      0.27       417
         Low       0.24      0.22      0.23       413
      Medium       0.27      0.30      0.28       438

    accuracy                           0.26      1694
   macro avg       0.25      0.25      0.25      1694
weighted avg       0.25      0.26      0.25      1694

In [34]:
df['low_satisfaction'] = df['customer_satisfaction_rating'] <= 2

df['high_priority_flag'] = df['ticket_priority'].isin(['High', 'Critical'])

df['long_resolution_flag'] = df['resolution_time_hours_capped'] > 72

In [31]:
import pandas as pd

# convert to datetime (safe even if already done)
df['date_of_purchase'] = pd.to_datetime(df['date_of_purchase'], errors='coerce')
df['time_to_resolution'] = pd.to_datetime(df['time_to_resolution'], errors='coerce')

# compute resolution time in hours
df['resolution_time_hours'] = (
    df['time_to_resolution'] - df['date_of_purchase']
).dt.total_seconds() / 3600

In [32]:
df['resolution_time_hours_capped'] = df['resolution_time_hours'].clip(upper=2160)

In [33]:
df['resolution_time_hours_capped'].describe()

count    2769.0
mean     2160.0
std         0.0
min      2160.0
25%      2160.0
50%      2160.0
75%      2160.0
max      2160.0
Name: resolution_time_hours_capped, dtype: float64

In [35]:
ticket_counts = df.groupby('customer_email').size()

df['repeat_customer_flag'] = df['customer_email'].map(ticket_counts) > 3

In [36]:
df['churn_score'] = (
    df['low_satisfaction'].fillna(False).astype(int) +
    df['high_priority_flag'].astype(int) +
    df['long_resolution_flag'].astype(int) +
    df['repeat_customer_flag'].astype(int)
)

In [37]:
def churn_label(score):
    if score >= 3:
        return 'High'
    elif score == 2:
        return 'Medium'
    else:
        return 'Low'

df['churn_risk'] = df['churn_score'].apply(churn_label)

In [38]:
df['churn_risk'].value_counts()

churn_risk
Low       6520
Medium    1360
High       589
Name: count, dtype: int64